---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    pgp: >-
      C430940539460ADB635449EAF49A52606CE72EA6
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    pgp: >-
      0514601ED08F6CD7E863F04B079CE7BDBA7D5DBB,
      C430940539460ADB635449EAF49A52606CE72EA6
