kind: Secret
ansible_user: ENC[AES256_GCM,data:OJJri5CJwQ==,iv:9gD47RVM/33aL7F7rFp1QSWzmZ2o+MmNf4YBwtam/as=,tag:glA2tzSv3MkcRzKG5Srp0g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:gERUxg5WAjX9/zI=,iv:jP1v6PcXsGjIUsHZ4GwizfUVxu6rV24vZAEWJ09sglQ=,tag:2q1/LoH9Xufgou3fZ7kPUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-04T19:29:45Z"
    mac: ENC[AES256_GCM,data:qf6hrgd0ZKCrvwRBtHw6bZ4O7Ir82M6ercS86ECdecsYUlx0x8kMq9FYPBX3IC7CuJqFqAK9QyzdG+SoqQyeyig8NnA96P4WqVim2fKFTdS/mGlpK9piCzXOso7RTLr26OWWF/+cIMvwpabYoqzu6vnQLTqFMR8XqsP9qqyyKxw=,iv:Yq8KNGPmEfHtICWOu/u501c2ixsOgo71i5LWG5AThn8=,tag:2j8hzlpM4PZDNf0UL0WfYA==,type:str]
    pgp:
        - created_at: "2021-10-04T19:29:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/8J7I8celMJARAAmiAJoBu9I0CwZJV817aJ19VtYPezl93zs6N7SnW9Q2hI
            GUCDS4Y432xRbjQQG+q80a1WJO9t9tqmHBkry7JDGCp4I4eAFVSyqFl/RjC5CW8U
            qWtl6vjcX412Ru0z6+86BHoCWUVLod5yEWsJCariHzSYZh7SiCNcdsi0Z10wWjSo
            0HSD/vMMUlxowOzQr1ISjr/fCOK4KQklCgmuVBYirslUfnzTTvzT7L079EHgBRXB
            gOp1CiTzf3fd2VnGwpEiazqL7IkkJlzi38KTHuT6nUC/VHrjrsE2ts/BqVV3kz7y
            ASQ+OQGGMa46V01vBQfTaLR2v4903/Tcphq7vZ50x6VSsfD9NUbEl7FD3tRDX88H
            pcHDMAxboXGuHuEJrV1eQbJ4LUC5nFUjB3b2m/XtXO0KB+HpV+a+N84kRStdW2iL
            5vnNYJ6UqBEw9gRX8RyVBDwvj3KKHqFAwjcbRDhN8rtJoyf4JE7Z/yK70B8w0JNm
            vQLEX8t5N6iX5a4rJdfljYsqFpcWX3HHpA9Icx0JBR75KlMeaPvdf2JlnIBRI7ni
            9zxn5/epIAnAQtR47iE0FWGN5e6zkmIUnbBJly/hF0rPGXtnZ9TNl61RRN9NYAbm
            +mOM86lYHM760iwhUE6N5aXPBUHfE67lvSS9JHfDD17nfkZoWMxyPQz/w5hyxFzS
            XgHnW9pOa0/CjN5JX9vPySbAwYCKHXlN7Cu1FxNOB0oYDD3BkKOd8cF1+xaEjAmD
            JVjDmvjdMkDb4ZvfrxH7+xmQ/gOs3Yyly2KxiMO9D24Sp3UXnL/FG4PeFnMybv0=
            =Nj7W
            -----END PGP MESSAGE-----
          fp: C430940539460ADB635449EAF49A52606CE72EA6
    unencrypted_regex: ^(kind)$
    version: 3.7.1
