---
<<<<<<< HEAD
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
=======
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
>>>>>>> template/main
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: core
  path: ./cluster/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
<<<<<<< HEAD
      name: sops-gpg
=======
      name: sops-age
>>>>>>> template/main
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
