---
<<<<<<< HEAD
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
=======
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
>>>>>>> template/main
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/crds
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
