apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
<<<<<<< HEAD
    - default
    - kube-system
    - networking
    - system-upgrade
    - media
=======
  - default
  - kube-system
  - networking
  - system-upgrade
>>>>>>> template/main
